name: Build Eleventy

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * *' # This schedule runs the job every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build
        env:
          ITCH_KEY: ${{ secrets.ITCH_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}